//package com.calculator.swing;
//Javaprogramtocreateasimplecalculator
//withbasic+,-,/,*usingjavaswingelements
importjava.awt.Color;
importjava.awt.event.ActionEvent;
importjava.awt.event.ActionListener;
importjavax.swing.JButton;
importjavax.swing.JFrame;
importjavax.swing.JPanel;
importjavax.swing.JTextField;
importjavax.swing.UIManager;
@SuppressWarnings("serial")
publicclassCalculatorSwingextendsJFrameimplementsActionListener{
//createaframe
staticJFrameframeToDisplay;
//createatextfield
staticJTextFieldlabeTextField;
//itstoretheoperandsandoperators
Stringstring0,string1,string2;
//constructor
CalculatorSwing(){
string0=string1=string2="";
}
//mainfunctiontojavaapplication
publicstaticvoidmain(Stringargs[]){
//createtheframetodisplaythescreen
frameToDisplay=newJFrame("MyCalculator");
try{
//usedtosetthelookandfeelfortheapplication
UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
}catch(Exceptionexception){
System.err.println(exception.getMessage());
}
//createtheclassobject
CalculatorSwingcalculatorSwing=newCalculatorSwing();
//createtextfield
labeTextField=newJTextField(16);
//settothenoneditable
labeTextField.setEditable(false);
//declaringnumbersbuttonsandoperatorsbuttons
JButtonbutton_0,button_1,button_2,button_3,button_4,button_5,button_6,button_7,button_8,button_9,
button_add,button_subtract,button_div,button_mul,button_dot,button_equal1,button_equal2;
//creatingnumbersbuttons
button_0=newJButton("0");
button_1=newJButton("1");
button_2=newJButton("2");
button_3=newJButton("3");
button_4=newJButton("4");
button_5=newJButton("5");
button_6=newJButton("6");
button_7=newJButton("7");
button_8=newJButton("8");
button_9=newJButton("9");
//creatingequalsbuttons
button_equal2=newJButton("=");
//creatingoperatorslike+,-,*,/buttons
button_add=newJButton("+");
button_subtract=newJButton("-");
button_div=newJButton("/");
button_mul=newJButton("*");
button_equal1=newJButton("C");
//creatingdot(.)buttons
button_dot=newJButton(".");
//creatingpanel
JPaneljPanel=newJPanel();
//addingactionlistenerstothebuttons
button_mul.addActionListener(calculatorSwing);
button_div.addActionListener(calculatorSwing);
button_subtract.addActionListener(calculatorSwing);
button_add.addActionListener(calculatorSwing);
button_9.addActionListener(calculatorSwing);
button_8.addActionListener(calculatorSwing);
button_7.addActionListener(calculatorSwing);
button_6.addActionListener(calculatorSwing);
button_5.addActionListener(calculatorSwing);
button_4.addActionListener(calculatorSwing);
button_3.addActionListener(calculatorSwing);
button_2.addActionListener(calculatorSwing);
button_1.addActionListener(calculatorSwing);
button_0.addActionListener(calculatorSwing);
button_dot.addActionListener(calculatorSwing);
button_equal1.addActionListener(calculatorSwing);
button_equal2.addActionListener(calculatorSwing);
//addallelementstothepanel
jPanel.add(labeTextField);
jPanel.add(button_add);
jPanel.add(button_1);
jPanel.add(button_2);
jPanel.add(button_3);
jPanel.add(button_subtract);
jPanel.add(button_4);
jPanel.add(button_5);
jPanel.add(button_6);
jPanel.add(button_mul);
jPanel.add(button_7);
jPanel.add(button_8);
jPanel.add(button_9);
jPanel.add(button_div);
jPanel.add(button_dot);
jPanel.add(button_0);
jPanel.add(button_equal1);
jPanel.add(button_equal2);
//setbackgroundofthepanel
jPanel.setBackground(Color.darkGray);
//addthepaneltotheframe
frameToDisplay.add(jPanel);
frameToDisplay.setSize(210,230);
frameToDisplay.show();
}
//actionlistenerimplementation
publicvoidactionPerformed(ActionEvente){
Stringinput=e.getActionCommand();
//checkifthegiven valueisnumber
if((input.charAt(0)>='0'&&input.charAt(0)<='9')||input.charAt(0)=='.'){
//ifoperandispresentthenaddtosecondno
if(!string1.equals(""))
string2=string2+input;
else
string0=string0+input;
//setthevaluetothetext
labeTextField.setText(string0+string1+string2);
}elseif(input.charAt(0)=='C'){
//clearing
string0=string1=string2="";
//setthevalueofthetext
labeTextField.setText(string0+string1+string2);
}elseif(input.charAt(0)=='='){
doubleequalsInput;
//storethevalueinthefirstindex
if(string1.equals("+"))
equalsInput=(Double.parseDouble(string0)+Double.parseDouble(string2));
elseif(string1.equals("-"))
equalsInput=(Double.parseDouble(string0)-Double.parseDouble(string2));
elseif(string1.equals("/"))
equalsInput=(Double.parseDouble(string0)/Double.parseDouble(string2));
else
equalsInput=(Double.parseDouble(string0)*Double.parseDouble(string2));
//setthevalueofthetext
labeTextField.setText(string0+string1+string2+"="+equalsInput);
//convertinginttostring
string0=Double.toString(equalsInput);
string1=string2="";
}else{
//ifnooperandisthere
if(string1.equals("")||string2.equals(""))
string1=input;
else{
doublete;
//storethevalueinthefirstindex
if(string1.equals("+"))
te=(Double.parseDouble(string0)+Double.parseDouble(string2));
elseif(string1.equals("-"))
te=(Double.parseDouble(string0)-Double.parseDouble(string2));
elseif(string1.equals("/"))
te=(Double.parseDouble(string0)/Double.parseDouble(string2));
else
te=(Double.parseDouble(string0)*Double.parseDouble(string2));
//convertinginttostring
string0=Double.toString(te);
//puttheoperator
string1=input;
//taketheoperandasblank
string2="";
}
//setthevalueofthetext
labeTextField.setText(string0+string1+string2);
}
}
}
